### ISSUE TITLE
Encode/Encrypt text message

### ISSUE THREAD

**Issue by wake-0** [CyberReboot/SEAL#37]
Hello everybody,

I wanted to encrypt a text message with PySEAL and then decrypt it. Now I noticed that there is no `Encoder` that uses a string as input for encoding a `Plaintext` object.

Is there a suitable solution for this e.g. has someone implemented an own `StringEncoder`?

**Comment by Arman001** [comment]
I don't think there is a StringEncoder for pyseal yet. I am currently just converting string to bits and then encrypting it with simple IntegerEncoder and it works fine. If there is another way then kindly inform me.

**Comment by wake-0** [comment]
@Arman001 what kind of encoding do you use for converting a string to int? Do you have any example code? 

Thanks in advance!

**Comment by Arman001** [comment]
@Blackjack92 may be it is  naive approach but you have to convert first string to bits like below
![image](https://user-images.githubusercontent.com/21517793/75237871-f05b6100-57e1-11ea-8f99-b56fa4f7bc80.png)
then you can convert resulting list into a numpy array and can do bit by bit encryption and then during decryption you will get bits and you can convert back to a string using
![image](https://user-images.githubusercontent.com/21517793/75238074-45977280-57e2-11ea-8230-a1c2f1dace7f.png)
I hope it helps.

**Comment by wake-0** [comment]
@Arman001  Thank you very much for the code snippets!
